// アイコンの種類
CONST_PZL1.ICONTYPE = [
    CONST_PZL1.IMGID.DOG_SHIBA,
    CONST_PZL1.IMGID.DOG_PAG,
    CONST_PZL1.IMGID.DOG_DALMATIAN,
    CONST_PZL1.IMGID.DOG_CORGI,
    CONST_PZL1.IMGID.DOG_LABRADOR,
    CONST_PZL1.IMGID.ITEM_BONE_SINGLE,
    CONST_PZL1.IMGID.ITEM_BONE_DOUBLE
]

CONST_PZL1.DOG_NUM = 5;

CONST_PZL1.ICONTYPE_ID = {
    DOG_SHIBA: 0,
    DOG_PAG: 1,
    DOG_DALMATIAN: 2,
    DOG_CORGI: 3,
    DOG_LABRADOR: 4,
}

CONST_PZL1.ITEMTYPE_ID = {
    ITEM_BONE_SINGLE: 5,
    ITEM_BONE_DOUBLE: 6
}

// 制限時間表示位置
CONST_PZL1.TIMEINFO = {
    INITTIME: 60,
    X: 16,
    Y: 40
}

// アイコン消去数の表示位置
CONST_PZL1.DELETEINFO = {
    X: 208,
    WIDTH: 160,
    Y: CONST_PZL1.ICON_DELETEINFO.HEIGHT / 2 + 16,
}

// アイテムを生成するための必要な消去数
CONST_PZL1.ICON_NUM = {
    ITEM_BONE_SINGLE: 5,
    ITEM_BONE_DOUBLE: 2,
};

// 消去するアイコンの種類数
CONST_PZL1.DELETE_TYPE_NUM = {
    ITEM_BONE_DOUBLE: 2,
}

// ボーナスアイコン表示位置
CONST_PZL1.BONUSINFO = {
    WIDTH: 180,
    Y: CONST_PZL1.ICON_DELETEINFO.HEIGHT / 2 + 16
}

CONST_PZL1.ITEMDELETE = {
    TIME: 400,
    SCALE: 0.6,
}

CONST_PZL1.ICONFADEIN = {
    TIME: 300,
    YDIST: CONST_PZL1.ICON.HEIGHT / 2,
}

CONST_PZL1.ICONDELETE = {
    TIME: 250,
}

CONST_PZL1.ICONFALL = {
    TIME: 300,
}

CONST_PZL1.DELETE_INTERVAL = CONST_PZL1.ICONFADEIN.TIME + CONST_PZL1.ICONFALL.TIME;