/* 共通変数 */
CONST_ACT1.COMMON_ACT1 = {
    // 文字の色
    FONTCOLOR_DEFAULT: "#ffffff",
    FONTSTYLE_NORMAL: "Bit12",
    FONTSTYLE_BOLD: "Bit12Bold",
    // フォントサイズ
    FONTSIZE_DEFAULT: 20,

    FONTSIZE_GAMEOVER: 48,
    FONTSIZE_RETRY: 24,

    // 背景色
    BGCOLOR_DEFAULT: "#808080",
    BGCOLOR_ACTION: "#80D0E8",
    // BGCOLOR_ACTION: "#000000",

};

