// 実績
CONST_STT1.ACHIEVE_BG = {
    COLOR: 0xffd0d0,
    ALPHA: 0.9,
    MARGIN: 36,
    ROUND: 24,
}

// 実績オブジェクト
CONST_STT1.ACHIEVE_OBJ = {
    WIDTH: 192,
    HEIGHT: 48,

    COLOR: 0xffd0d0,
    COLOR_DONE: 0xff8080,
    ROUND: 16,
    SPACE: 20,

    FONTCOLOR: "#000000",
    FONTSIZE: 16,

    FONTSTYLE_NORMAL: "Bit12",
    FONTSTYLE_BOLD: "Bit12Bold",
}

// 実績カテゴリ別タイトル
CONST_STT1.ACHIEVE_CATEGORY_TITLE = {
    FONTCOLOR: "#000000",
    FONTSIZE: 96,
    FONTSTYLE_NORMAL: "Bit12",
    FONTSTYLE_BOLD: "Bit12Bold",
};

// 表示列数
CONST_STT1.ACHIEVE_COL = 4;